# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaEE0EMDZqIZQSRjwJ8-wpMq_yZIHV2Q
"""

# @title Default title text
print("Credit Card Fraud Detection Project")

import pandas as pd

print("Pandas loaded successfully")

pd.read_csv(...)

import kagglehub

path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

import os

print(os.listdir(path))

df = pd.read_csv(path + "/creditcard.csv")

print("Dataset loaded successfully")

df.head()

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

duplicate_count = df.duplicated().sum()
total_rows = len(df)

duplicate_percentage = (duplicate_count / total_rows) * 100

print("Duplicate rows:", duplicate_count)
print("Total rows:", total_rows)
print("Duplicate percentage:", round(duplicate_percentage, 2), "%")

df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

df["Class"].value_counts()

fraud_percentage = (df["Class"].value_counts(normalize=True) * 100)

print(fraud_percentage)

import matplotlib.pyplot as plt

class_counts = df["Class"].value_counts()

plt.figure(figsize=(6, 4))
plt.bar(["Normal", "Fraud"], class_counts.values)
plt.title("Normal vs Fraud Transactions")
plt.xlabel("Transaction Type")
plt.ylabel("Number of Transactions")
plt.show()

df["Amount"].describe()

df.groupby("Class")["Amount"].mean()

df.groupby("Class")["Amount"].median()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

plt.hist(df[df["Class"] == 0]["Amount"], bins=50, alpha=0.6, label="Normal")
plt.hist(df[df["Class"] == 1]["Amount"], bins=50, alpha=0.6, label="Fraud")

plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.title("Transaction Amount Distribution: Normal vs Fraud")
plt.legend()

plt.show()

df.groupby("Class")["Time"].mean()

df["Hour"] = (df["Time"] // 3600) % 24

df[["Time", "Hour", "Class"]].head()

fraud_by_hour = df[df["Class"] == 1].groupby("Hour").size()

print(fraud_by_hour)

hour_summary = df.groupby("Hour")["Class"].agg(
    total_transactions="count",
    fraud_transactions="sum"
)

hour_summary["fraud_rate"] = (
    hour_summary["fraud_transactions"]
    / hour_summary["total_transactions"]
) * 100

hour_summary

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.plot(
    hour_summary.index,
    hour_summary["fraud_rate"],
    marker="o"
)

plt.xlabel("Hour")
plt.ylabel("Fraud Rate (%)")
plt.title("Fraud Rate by Hour")
plt.xticks(range(24))
plt.grid(True, alpha=0.3)

plt.show()

X = df.drop(columns=["Class", "Hour"])
y = df["Class"]

print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed")

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_scaled, y_train)

print("Model training completed")

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Predictions completed")
print("First 20 predictions:")
print(y_pred[:20])

import numpy as np

unique, counts = np.unique(y_pred, return_counts=True)

print(dict(zip(unique, counts)))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

print(cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

results = {
    "Model": "Logistic Regression",
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1 Score": f1_score(y_test, y_pred)
}

print(results)

"""# New Section"""